dataset: /zhome/ea/6/187439/understandable-ProtoPNet/datasets/cub200
exp_name: as_is_run
architecture: resnet34
num_prototypes: 2000
epochs: 501
img_size: 224
batch_size: 128
warm_epochs: 50
step_size: 150
test_interval: 50
push_interval: 300
prototype_activation_function: log
add_on_layers: regular
min_diversity: 0.1
diversity_coeff: 0.1
gpus: 0
num_workers: 8
seed: 42
no_ppnet: False
